
package visao;

import controle.ModeloTabela;
import java.awt.Color;
import java.awt.Component;
import java.awt.Graphics;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicMenuBarUI;
import modelo.Analisador;
import modelo.TipoToken;
import modelo.Token;

/**
 * @author Claudio Sumburane
 * @author Herquiloide Hele
 * @author Jose Seie
 * 
 */
public class JanelaEditor extends javax.swing.JFrame {

   
    private ArrayList<Token> lista = new ArrayList<>();
    private String colunas [] = {"Linha", "Token", "Tipo", "Tamanho"};
    private ModeloTabela modelo = new ModeloTabela(lista, colunas);
    
    public JanelaEditor() {
        initComponents();
        NumeroLinhas linhas = new NumeroLinhas();
        jtePane.setBorder(linhas);
        jtToken.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jbRun = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jpCodigo = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtePane = new javax.swing.JEditorPane();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtToken = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Analizador Lexico");

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(1061, 40));

        jButton4.setBackground(new java.awt.Color(30, 144, 255));
        jButton4.setFont(new java.awt.Font("Droid Serif", 0, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/new_file.png"))); // NOI18N
        jButton4.setBorder(null);
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.setFocusPainted(false);

        jButton3.setBackground(new java.awt.Color(30, 144, 255));
        jButton3.setFont(new java.awt.Font("Droid Serif", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/salvar.png"))); // NOI18N
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setFocusPainted(false);

        jbRun.setBackground(new java.awt.Color(30, 144, 255));
        jbRun.setFont(new java.awt.Font("Droid Serif", 0, 14)); // NOI18N
        jbRun.setForeground(new java.awt.Color(255, 255, 255));
        jbRun.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/run.png"))); // NOI18N
        jbRun.setBorder(null);
        jbRun.setContentAreaFilled(false);
        jbRun.setFocusPainted(false);
        jbRun.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbRunMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbRunMouseExited(evt);
            }
        });
        jbRun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRunActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(30, 144, 255));
        jButton5.setFont(new java.awt.Font("Droid Serif", 0, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/open_folder.png"))); // NOI18N
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jButton5.setFocusPainted(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(344, 344, 344)
                .addComponent(jbRun, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jbRun, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.Y_AXIS));

        jpCodigo.setBackground(new java.awt.Color(0, 51, 255));
        jpCodigo.setLayout(new java.awt.BorderLayout());

        jtePane.setFont(new java.awt.Font("Droid Serif", 0, 16)); // NOI18N
        jtePane.setMinimumSize(new java.awt.Dimension(106, 200));
        jtePane.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtePaneKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtePaneKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtePaneKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jtePane);

        jpCodigo.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel3.add(jpCodigo);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setPreferredSize(new java.awt.Dimension(1061, 220));
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));

        jtToken.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Linha", "Token", "Tipo", "coluna"
            }
        ));
        jScrollPane2.setViewportView(jtToken);

        jPanel4.add(jScrollPane2);

        jPanel3.add(jPanel4);

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        jMenuBar1.setForeground(new java.awt.Color(204, 204, 204));

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Formatar");
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Ferramentas");
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);
        jMenuBar1.setUI(new BasicMenuBarUI(){
            public void paint(Graphics g, Component c){
                g.setColor(Color.WHITE);
                g.fillRect(0, 0, c.getWidth(), c.getHeight());
            }

        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 527, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbRunMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbRunMouseExited
        jbRun.setBackground(new Color(30, 144, 255));
    }//GEN-LAST:event_jbRunMouseExited

    private void jbRunMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbRunMouseEntered
        jbRun.setBackground(new Color(20, 20, 240));
    }//GEN-LAST:event_jbRunMouseEntered

    private void jbRunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRunActionPerformed
        if(jtePane.getText().isEmpty())
            JOptionPane.showMessageDialog(null, "Nao foi encontrado nenhum codigo");
        else{
            lista.clear();
            lista = Analisador.getTokens(jtePane.getText());
            modelo.setLista(lista);
            this.pintarLinha();
        } 
    }//GEN-LAST:event_jbRunActionPerformed

    private void jtePaneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtePaneKeyPressed

    }//GEN-LAST:event_jtePaneKeyPressed

    private void jtePaneKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtePaneKeyReleased
                       
    }//GEN-LAST:event_jtePaneKeyReleased

    private void jtePaneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtePaneKeyTyped
        
    }//GEN-LAST:event_jtePaneKeyTyped

    
    public void pintarLinha(){
        ArrayList<Integer> bugs = new ArrayList<>();
        
        for (int i=0; i<lista.size(); i++){
            if(lista.get(i).getTipo() == TipoToken.Erro){
                bugs.add(i);
            }
        }
        
//        jtToken.setDefaultRenderer(Object.class, new ErrorLine(bugs));
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaEditor().setVisible(true);
                            
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbRun;
    private javax.swing.JPanel jpCodigo;
    private javax.swing.JTable jtToken;
    private javax.swing.JEditorPane jtePane;
    // End of variables declaration//GEN-END:variables
}
